FROM rabbitmq:3.13-management
LABEL authors="woopaca"

ENV RABBITMQ_DEFAULT_USER=chat
ENV RABBITMQ_DEFAULT_PASS=chat

EXPOSE 5672
EXPOSE 15672
EXPOSE 61613

VOLUME /var/lib/rabbitmq

RUN mkdir -p /etc/rabbitmq
COPY rabbitmq.conf /etc/rabbitmq/rabbitmq.conf

RUN rabbitmq-plugins enable rabbitmq_stomp

CMD ["rabbitmq-server", "-c", "/etc/rabbitmq/rabbitmq.conf"]
